# Generated by Django 2.2.2 on 2019-06-23 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
